repos:
-   repo: local
    hooks:
    - id: flake8
      name: flake8Black
      language: system
      entry: bash -c '. .venv/bin/activate && black . && flake8 .'
      always_run: false
      pass_filenames: true
      stages: [commit]
-   repo: local
    hooks:
    - id: pydocstyle
      name: pydocstyle
      language: system
      entry: bash -c '. .venv/bin/activate && pydocstyle .'
      always_run: false
      pass_filenames: true
      stages: [commit]
-   repo: local
    hooks:
    - id: mypy
      name: mypy
      language: system
      entry: bash -c '. .venv/bin/activate && mypy .'
      always_run: false
      pass_filenames: true
      stages: [commit]
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '. .venv/bin/activate && .venv/bin/pip3 freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]